vl_compilenn('enableGpu', true, ...
               'cudaMethod', 'nvcc', ...
               'cudaRoot', '/usr/local/cuda-8.0', ...
               'enableCudnn', true, ...
               'cudnnRoot', '/usr/local/cuda-8.0/lib64')